### ISSUE TITLE
Please upgrade dockerfilelint to support multi-stage builds

### ISSUE THREAD

**Issue by nexdrew** [replicatedhq/fromlatest.io#242]
See replicatedhq/dockerfilelint#93

The `dockerfilelint` package supports linting Dockerfiles with multi-stage builds as of version 1.4.0 (released Sept 12 2017).

Since folks are using fromlatest.io as a reference for what the linter can do, we should upgrade the dependency here and deploy an update to fromlatest.io. Hopefully it's not too much of a pain.

Without server access, I'm not sure how much I can actually help, but please let me know if I can.

Thanks for the building and supporting these awesome free tools!

**Comment by hayd** [comment]
This is still the case.

**Comment by Attoy** [comment]
It looks like this is still an ongoing issue
